from raptor import BaseQAModel
from models.model import Model

class MistralQAModel(BaseQAModel):
    def __init__(self):
        self.model = Model("MIXTRAL")

    def answer_question(self, context, question):
        """
        Generates an answer to a given question based on the provided context
        using the Gemini model configured in the Model class.

        Args:
            context (str): The text that provides context for the question.
            question (str): The question that needs an answer.

        Returns:
            str: The answer generated by the Gemini model.
        """
        prompt = f"Given the context: {context} Answer the following question: {question}"
        answer = self.model.query(prompt)
        return answer